// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package spec

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActiveListenerSessionClientDeviceCategory.
const (
	ActiveListenerSessionClientDeviceCategoryOther ActiveListenerSessionClientDeviceCategory = "Other"
)

// Valid indicates whether the value is a known member of the ActiveListenerSessionClientDeviceCategory enum.
func (e ActiveListenerSessionClientDeviceCategory) Valid() bool {
	switch e {
	case ActiveListenerSessionClientDeviceCategoryOther:
		return true
	default:
		return false
	}
}

// Defines values for ActiveMemberSessionClientDeviceCategory.
const (
	ActiveMemberSessionClientDeviceCategoryBrowser      ActiveMemberSessionClientDeviceCategory = "browser"
	ActiveMemberSessionClientDeviceCategoryMobile       ActiveMemberSessionClientDeviceCategory = "mobile"
	ActiveMemberSessionClientDeviceCategoryNativeMobile ActiveMemberSessionClientDeviceCategory = "native_mobile"
	ActiveMemberSessionClientDeviceCategoryOther        ActiveMemberSessionClientDeviceCategory = "other"
)

// Valid indicates whether the value is a known member of the ActiveMemberSessionClientDeviceCategory enum.
func (e ActiveMemberSessionClientDeviceCategory) Valid() bool {
	switch e {
	case ActiveMemberSessionClientDeviceCategoryBrowser:
		return true
	case ActiveMemberSessionClientDeviceCategoryMobile:
		return true
	case ActiveMemberSessionClientDeviceCategoryNativeMobile:
		return true
	case ActiveMemberSessionClientDeviceCategoryOther:
		return true
	default:
		return false
	}
}

// Defines values for OnboardingSuggestionItemType.
const (
	OnboardingSuggestionItemTypeChannel  OnboardingSuggestionItemType = "channel"
	OnboardingSuggestionItemTypePlaylist OnboardingSuggestionItemType = "playlist"
)

// Valid indicates whether the value is a known member of the OnboardingSuggestionItemType enum.
func (e OnboardingSuggestionItemType) Valid() bool {
	switch e {
	case OnboardingSuggestionItemTypeChannel:
		return true
	case OnboardingSuggestionItemTypePlaylist:
		return true
	default:
		return false
	}
}

// Defines values for PremiumPassStatus.
const (
	Active      PremiumPassStatus = "active"
	Expired     PremiumPassStatus = "expired"
	Ready       PremiumPassStatus = "ready"
	Unavailable PremiumPassStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the PremiumPassStatus enum.
func (e PremiumPassStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Expired:
		return true
	case Ready:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for SkipRulesetListenerType.
const (
	SkipRulesetListenerTypeGuest   SkipRulesetListenerType = "guest"
	SkipRulesetListenerTypePremium SkipRulesetListenerType = "premium"
	SkipRulesetListenerTypePublic  SkipRulesetListenerType = "public"
)

// Valid indicates whether the value is a known member of the SkipRulesetListenerType enum.
func (e SkipRulesetListenerType) Valid() bool {
	switch e {
	case SkipRulesetListenerTypeGuest:
		return true
	case SkipRulesetListenerTypePremium:
		return true
	case SkipRulesetListenerTypePublic:
		return true
	default:
		return false
	}
}

// Defines values for SkipRulesetWindowUnit.
const (
	SkipRulesetWindowUnitDays    SkipRulesetWindowUnit = "days"
	SkipRulesetWindowUnitHours   SkipRulesetWindowUnit = "hours"
	SkipRulesetWindowUnitMinutes SkipRulesetWindowUnit = "minutes"
	SkipRulesetWindowUnitMonths  SkipRulesetWindowUnit = "months"
	SkipRulesetWindowUnitSeconds SkipRulesetWindowUnit = "seconds"
	SkipRulesetWindowUnitWeeks   SkipRulesetWindowUnit = "weeks"
	SkipRulesetWindowUnitYears   SkipRulesetWindowUnit = "years"
)

// Valid indicates whether the value is a known member of the SkipRulesetWindowUnit enum.
func (e SkipRulesetWindowUnit) Valid() bool {
	switch e {
	case SkipRulesetWindowUnitDays:
		return true
	case SkipRulesetWindowUnitHours:
		return true
	case SkipRulesetWindowUnitMinutes:
		return true
	case SkipRulesetWindowUnitMonths:
		return true
	case SkipRulesetWindowUnitSeconds:
		return true
	case SkipRulesetWindowUnitWeeks:
		return true
	case SkipRulesetWindowUnitYears:
		return true
	default:
		return false
	}
}

// Defines values for SkipRulesetWithSkipsRemainingListenerType.
const (
	SkipRulesetWithSkipsRemainingListenerTypeGuest   SkipRulesetWithSkipsRemainingListenerType = "guest"
	SkipRulesetWithSkipsRemainingListenerTypePremium SkipRulesetWithSkipsRemainingListenerType = "premium"
	SkipRulesetWithSkipsRemainingListenerTypePublic  SkipRulesetWithSkipsRemainingListenerType = "public"
)

// Valid indicates whether the value is a known member of the SkipRulesetWithSkipsRemainingListenerType enum.
func (e SkipRulesetWithSkipsRemainingListenerType) Valid() bool {
	switch e {
	case SkipRulesetWithSkipsRemainingListenerTypeGuest:
		return true
	case SkipRulesetWithSkipsRemainingListenerTypePremium:
		return true
	case SkipRulesetWithSkipsRemainingListenerTypePublic:
		return true
	default:
		return false
	}
}

// Defines values for SkipRulesetWithSkipsRemainingWindowUnit.
const (
	SkipRulesetWithSkipsRemainingWindowUnitDays    SkipRulesetWithSkipsRemainingWindowUnit = "days"
	SkipRulesetWithSkipsRemainingWindowUnitHours   SkipRulesetWithSkipsRemainingWindowUnit = "hours"
	SkipRulesetWithSkipsRemainingWindowUnitMinutes SkipRulesetWithSkipsRemainingWindowUnit = "minutes"
	SkipRulesetWithSkipsRemainingWindowUnitMonths  SkipRulesetWithSkipsRemainingWindowUnit = "months"
	SkipRulesetWithSkipsRemainingWindowUnitSeconds SkipRulesetWithSkipsRemainingWindowUnit = "seconds"
	SkipRulesetWithSkipsRemainingWindowUnitWeeks   SkipRulesetWithSkipsRemainingWindowUnit = "weeks"
	SkipRulesetWithSkipsRemainingWindowUnitYears   SkipRulesetWithSkipsRemainingWindowUnit = "years"
)

// Valid indicates whether the value is a known member of the SkipRulesetWithSkipsRemainingWindowUnit enum.
func (e SkipRulesetWithSkipsRemainingWindowUnit) Valid() bool {
	switch e {
	case SkipRulesetWithSkipsRemainingWindowUnitDays:
		return true
	case SkipRulesetWithSkipsRemainingWindowUnitHours:
		return true
	case SkipRulesetWithSkipsRemainingWindowUnitMinutes:
		return true
	case SkipRulesetWithSkipsRemainingWindowUnitMonths:
		return true
	case SkipRulesetWithSkipsRemainingWindowUnitSeconds:
		return true
	case SkipRulesetWithSkipsRemainingWindowUnitWeeks:
		return true
	case SkipRulesetWithSkipsRemainingWindowUnitYears:
		return true
	default:
		return false
	}
}

// ActiveListenerSession defines model for ActiveListenerSession.
type ActiveListenerSession struct {
	ClientDeviceCategory    *ActiveListenerSessionClientDeviceCategory `json:"client_device_category,omitempty"`
	ClientDeviceDescription *string                                    `json:"client_device_description,omitempty"`
	Key                     *int                                       `json:"key,omitempty"`
	LastPlayedAt            *string                                    `json:"last_played_at,omitempty"`
}

// ActiveListenerSessionClientDeviceCategory defines model for ActiveListenerSession.ClientDeviceCategory.
type ActiveListenerSessionClientDeviceCategory string

// ActiveMemberSession defines model for ActiveMemberSession.
type ActiveMemberSession struct {
	ClientDeviceCategory    *ActiveMemberSessionClientDeviceCategory `json:"client_device_category,omitempty"`
	ClientDeviceDescription *string                                  `json:"client_device_description,omitempty"`
	Key                     *string                                  `json:"key,omitempty"`
	LastPlayedAt            *string                                  `json:"last_played_at,omitempty"`
}

// ActiveMemberSessionClientDeviceCategory defines model for ActiveMemberSession.ClientDeviceCategory.
type ActiveMemberSessionClientDeviceCategory string

// Channel defines model for Channel.
type Channel struct {
	AdDfpUnitId      *string `json:"ad_dfp_unit_id,omitempty"`
	Description      *string `json:"description,omitempty"`
	DescriptionLong  *string `json:"description_long,omitempty"`
	DescriptionShort *string `json:"description_short,omitempty"`
	Id               int     `json:"id"`
	Images           *Image  `json:"images,omitempty"`
	Key              string  `json:"key"`
	Name             string  `json:"name"`
}

// ChannelFilter defines model for ChannelFilter.
type ChannelFilter struct {
	Channels           *[]Channel `json:"channels,omitempty"`
	DescriptionText    *string    `json:"description_text,omitempty"`
	DescriptionTitle   *string    `json:"description_title,omitempty"`
	Display            *bool      `json:"display,omitempty"`
	DisplayDescription *bool      `json:"display_description,omitempty"`
	Genre              *bool      `json:"genre,omitempty"`
	Id                 *int       `json:"id,omitempty"`
	Key                string     `json:"key"`
	Meta               *bool      `json:"meta,omitempty"`
	Name               *string    `json:"name,omitempty"`
	NetworkId          int        `json:"network_id"`
	Position           *int       `json:"position,omitempty"`
}

// ChannelFilterShallow defines model for ChannelFilterShallow.
type ChannelFilterShallow struct {
	ChannelIds         *[]int  `json:"channel_ids,omitempty"`
	DescriptionText    *string `json:"description_text,omitempty"`
	DescriptionTitle   *string `json:"description_title,omitempty"`
	Display            *bool   `json:"display,omitempty"`
	DisplayDescription *bool   `json:"display_description,omitempty"`
	Genre              *bool   `json:"genre,omitempty"`
	Id                 *int    `json:"id,omitempty"`
	Key                string  `json:"key"`
	Meta               *bool   `json:"meta,omitempty"`
	Name               *string `json:"name,omitempty"`
	NetworkId          int     `json:"network_id"`
	Position           *int    `json:"position,omitempty"`
}

// ChannelSearchResult defines model for ChannelSearchResult.
type ChannelSearchResult struct {
	Id     int    `json:"id"`
	Images Image  `json:"images"`
	Key    string `json:"key"`
	Name   string `json:"name"`
}

// DataPreference defines model for DataPreference.
type DataPreference struct {
	ConsentedAt            *time.Time `json:"consented_at,omitempty"`
	Gdpr                   *bool      `json:"gdpr,omitempty"`
	Id                     *int       `json:"id,omitempty"`
	MarketingAndPromotions *bool      `json:"marketing_and_promotions,omitempty"`
	MemberId               *int       `json:"member_id,omitempty"`
	NetworkId              *int       `json:"network_id,omitempty"`
	Newsletters            *bool      `json:"newsletters,omitempty"`
	PersonalizeAds         *bool      `json:"personalize_ads,omitempty"`
}

// Device defines model for Device.
type Device struct {
	AppVersion      *string `json:"app_version,omitempty"`
	Category        *string `json:"category,omitempty"`
	Name            *string `json:"name,omitempty"`
	OperatingSystem *string `json:"operating_system,omitempty"`
	OsVersion       *string `json:"os_version,omitempty"`
}

// Facet defines model for Facet.
type Facet struct {
	Active bool   `json:"active"`
	Count  int    `json:"count"`
	Field  string `json:"field"`
	Label  string `json:"label"`
	Name   string `json:"name"`
}

// Image defines model for Image.
type Image struct {
	Default          string `json:"default"`
	HorizontalBanner string `json:"horizontal_banner"`
}

// LightChannelFilter defines model for LightChannelFilter.
type LightChannelFilter struct {
	Id         *int    `json:"id,omitempty"`
	Key        *string `json:"key,omitempty"`
	Name       *string `json:"name,omitempty"`
	ShowsCount *int    `json:"shows_count,omitempty"`
}

// LightEpisodeList defines model for LightEpisodeList.
type LightEpisodeList struct {
	ArtistsTagline *string  `json:"artists_tagline,omitempty"`
	Free           *bool    `json:"free,omitempty"`
	Images         *Image   `json:"images,omitempty"`
	Name           *string  `json:"name,omitempty"`
	Show           *Show    `json:"show,omitempty"`
	Slug           *string  `json:"slug,omitempty"`
	StartAt        *string  `json:"start_at,omitempty"`
	Tracks         *[]Track `json:"tracks,omitempty"`
}

// LightEventPresenter defines model for LightEventPresenter.
type LightEventPresenter struct {
	ArtistsTagline  *string                  `json:"artists_tagline,omitempty"`
	DescriptionHtml *string                  `json:"description_html,omitempty"`
	Duration        *int                     `json:"duration,omitempty"`
	EndAt           *string                  `json:"end_at,omitempty"`
	Id              *int                     `json:"id,omitempty"`
	Name            *string                  `json:"name,omitempty"`
	Show            *LightEventShowPresenter `json:"show,omitempty"`
	Slug            *string                  `json:"slug,omitempty"`
	StartAt         *string                  `json:"start_at,omitempty"`
	Subtitle        *string                  `json:"subtitle,omitempty"`
	Tracks          *[]Track                 `json:"tracks,omitempty"`
}

// LightEventShowPresenter defines model for LightEventShowPresenter.
type LightEventShowPresenter struct {
	ArtistsTagline        *string   `json:"artists_tagline,omitempty"`
	ChannelId             *int      `json:"channel_id,omitempty"`
	HumanReadableSchedule *[]string `json:"human_readable_schedule,omitempty"`
	Id                    *int      `json:"id,omitempty"`
	Images                *Image    `json:"images,omitempty"`
	Name                  *string   `json:"name,omitempty"`
	Slug                  *string   `json:"slug,omitempty"`
}

// LightPlaylist defines model for LightPlaylist.
type LightPlaylist struct {
	ChannelFilterIds *[]int                  `json:"channel_filter_ids,omitempty"`
	ChannelId        *int                    `json:"channel_id,omitempty"`
	Curator          *map[string]interface{} `json:"curator,omitempty"`
	Description      *string                 `json:"description,omitempty"`
	Duration         *string                 `json:"duration,omitempty"`
	FollowCount      *int                    `json:"follow_count,omitempty"`
	Id               int                     `json:"id"`
	Images           *Image                  `json:"images,omitempty"`
	Length           *int                    `json:"length,omitempty"`
	Name             string                  `json:"name"`
	PlayCount        *int                    `json:"play_count,omitempty"`
	Popularity       *float32                `json:"popularity,omitempty"`
	Slug             string                  `json:"slug"`
	Tags             *[]struct {
		Id   *int    `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"tags,omitempty"`
	TrackCount *int `json:"track_count,omitempty"`
}

// LightShow defines model for LightShow.
type LightShow struct {
	Active                *bool               `json:"active,omitempty"`
	ArtistsTagline        *string             `json:"artists_tagline,omitempty"`
	ChannelFilterIds      *[]int              `json:"channel_filter_ids,omitempty"`
	ChannelIds            *[]int              `json:"channel_ids,omitempty"`
	FollowsCount          *int                `json:"follows_count,omitempty"`
	HumanReadableSchedule *[]string           `json:"human_readable_schedule,omitempty"`
	Id                    *int                `json:"id,omitempty"`
	Images                *Image              `json:"images,omitempty"`
	Name                  *string             `json:"name,omitempty"`
	NextEndAt             *openapi_types.Date `json:"next_end_at,omitempty"`
	NextStartAt           *openapi_types.Date `json:"next_start_at,omitempty"`
	Slug                  *string             `json:"slug,omitempty"`
}

// MemberExperimentInput defines model for MemberExperimentInput.
type MemberExperimentInput struct {
	ExperimentId   int64   `json:"experiment_id"`
	ExperimentName *string `json:"experiment_name,omitempty"`
	VariantId      int32   `json:"variant_id"`
	VariantName    *string `json:"variant_name,omitempty"`
}

// Network defines model for Network.
type Network struct {
	Key  *string `json:"key,omitempty"`
	Name *string `json:"name,omitempty"`
}

// OnboardingResult defines model for OnboardingResult.
type OnboardingResult struct {
	ClientPlatformBit *int    `json:"client_platform_bit,omitempty"`
	CreatedAt         *string `json:"created_at,omitempty"`
	Id                *int    `json:"id,omitempty"`
	SelectedItems     *[]struct {
		Auto     *bool   `json:"auto,omitempty"`
		Id       *int    `json:"id,omitempty"`
		ItemId   *int    `json:"item_id,omitempty"`
		ItemType *string `json:"item_type,omitempty"`
	} `json:"selected_items,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// OnboardingSuggestion defines model for OnboardingSuggestion.
type OnboardingSuggestion struct {
	ChannelFilterId *int                          `json:"channel_filter_id,omitempty"`
	Images          *Image                        `json:"images,omitempty"`
	ItemId          *int                          `json:"item_id,omitempty"`
	ItemType        *OnboardingSuggestionItemType `json:"item_type,omitempty"`
	Name            *string                       `json:"name,omitempty"`
}

// OnboardingSuggestionItemType defines model for OnboardingSuggestion.ItemType.
type OnboardingSuggestionItemType string

// OnboardingTrackSample defines model for OnboardingTrackSample.
type OnboardingTrackSample struct {
	ContentLength *int    `json:"content_length,omitempty"`
	ContentUrl    *string `json:"content_url,omitempty"`
	Id            *int    `json:"id,omitempty"`
	Title         *string `json:"title,omitempty"`
}

// PremiumPass defines model for PremiumPass.
type PremiumPass struct {
	// ActivatedAt Timestamp at activation (nil for ready state).
	ActivatedAt *string `json:"activated_at,omitempty"`

	// DurationDays Duration for which a premium pass is active, configured in platform, 2-7 days
	DurationDays *int `json:"duration_days,omitempty"`

	// ExpiresAt Timestamp at expiration (nil for ready state).
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Status Current state of premium pass
	Status *PremiumPassStatus `json:"status,omitempty"`
}

// PremiumPassStatus Current state of premium pass
type PremiumPassStatus string

// Show defines model for Show.
type Show struct {
	Active                bool               `json:"active"`
	ArtistsTagline        string             `json:"artists_tagline"`
	Channels              []Channel          `json:"channels"`
	Description           string             `json:"description"`
	DescriptionHtml       string             `json:"description_html"`
	Duration              int                `json:"duration"`
	FacebookImages        *Image             `json:"facebook_images,omitempty"`
	Following             bool               `json:"following"`
	HumanReadableSchedule []string           `json:"human_readable_schedule"`
	Id                    int                `json:"id"`
	Images                Image              `json:"images"`
	MostRecentEvents      []ShowEvent        `json:"most_recent_events"`
	Name                  string             `json:"name"`
	NextEndAt             openapi_types.Date `json:"next_end_at"`
	NextStartAt           openapi_types.Date `json:"next_start_at"`
	OndemandEpisodeCount  int                `json:"ondemand_episode_count"`
	Slug                  string             `json:"slug"`
	Tagline               string             `json:"tagline"`
	UpcomingEvent         ShowEvent          `json:"upcoming_event"`
}

// ShowEvent defines model for ShowEvent.
type ShowEvent struct {
	ArtistsTagline  *string             `json:"artists_tagline,omitempty"`
	DescriptionHtml *string             `json:"description_html,omitempty"`
	Duration        *int                `json:"duration,omitempty"`
	EndAt           *openapi_types.Date `json:"end_at,omitempty"`
	Id              int                 `json:"id"`
	Images          *Image              `json:"images,omitempty"`
	Name            string              `json:"name"`
	ShowId          *int                `json:"show_id,omitempty"`
	Slug            *string             `json:"slug,omitempty"`
	StartAt         *openapi_types.Date `json:"start_at,omitempty"`
	Subtitle        *string             `json:"subtitle,omitempty"`
}

// ShowSearchResult defines model for ShowSearchResult.
type ShowSearchResult struct {
	Active                bool                  `json:"active"`
	ArtistsTagline        string                `json:"artists_tagline"`
	Channels              []ChannelSearchResult `json:"channels"`
	FollowersCount        int                   `json:"followers_count"`
	Following             bool                  `json:"following"`
	HumanReadableSchedule []string              `json:"human_readable_schedule"`
	Id                    int                   `json:"id"`
	Images                Image                 `json:"images"`
	Name                  string                `json:"name"`
	NextEndAt             openapi_types.Date    `json:"next_end_at"`
	NextStartAt           openapi_types.Date    `json:"next_start_at"`
	NowPlaying            bool                  `json:"now_playing"`
	OndemandEpisodeCount  int                   `json:"ondemand_episode_count"`
	Slug                  string                `json:"slug"`
}

// ShowSearchResults defines model for ShowSearchResults.
type ShowSearchResults struct {
	Metadata []Facet            `json:"metadata"`
	Results  []ShowSearchResult `json:"results"`
}

// SkipRuleset defines model for SkipRuleset.
type SkipRuleset struct {
	Limit          int                     `json:"limit"`
	ListenerType   SkipRulesetListenerType `json:"listener_type"`
	Territories    []string                `json:"territories"`
	WindowDuration int                     `json:"window_duration"`
	WindowUnit     SkipRulesetWindowUnit   `json:"window_unit"`
}

// SkipRulesetListenerType defines model for SkipRuleset.ListenerType.
type SkipRulesetListenerType string

// SkipRulesetWindowUnit defines model for SkipRuleset.WindowUnit.
type SkipRulesetWindowUnit string

// SkipRulesetWithSkipsRemaining defines model for SkipRulesetWithSkipsRemaining.
type SkipRulesetWithSkipsRemaining struct {
	ExpiresAt      *string                                   `json:"expires_at,omitempty"`
	Limit          int                                       `json:"limit"`
	ListenerType   SkipRulesetWithSkipsRemainingListenerType `json:"listener_type"`
	SkipsRemaining int                                       `json:"skips_remaining"`
	Territories    []string                                  `json:"territories"`
	WindowDuration int                                       `json:"window_duration"`
	WindowUnit     SkipRulesetWithSkipsRemainingWindowUnit   `json:"window_unit"`
}

// SkipRulesetWithSkipsRemainingListenerType defines model for SkipRulesetWithSkipsRemaining.ListenerType.
type SkipRulesetWithSkipsRemainingListenerType string

// SkipRulesetWithSkipsRemainingWindowUnit defines model for SkipRulesetWithSkipsRemaining.WindowUnit.
type SkipRulesetWithSkipsRemainingWindowUnit string

// StreamingMemberSession defines model for StreamingMemberSession.
type StreamingMemberSession struct {
	Device    *Device  `json:"device,omitempty"`
	Network   *Network `json:"network,omitempty"`
	SessionId *int     `json:"session_id,omitempty"`
	StartedAt *string  `json:"started_at,omitempty"`
}

// Track defines model for Track.
type Track struct {
	ArtUrl    *string    `json:"art_url,omitempty"`
	Artist    *string    `json:"artist,omitempty"`
	Duration  *int       `json:"duration,omitempty"`
	Id        *int       `json:"id,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
	Title     *string    `json:"title,omitempty"`

	// Track raw 'Artist - Title' string
	Track *string `json:"track,omitempty"`
}
